# Generated by Django 4.0.3 on 2022-04-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_email_alter_customer_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='email',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
