# Generated by Django 4.0.3 on 2022-04-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_coupon_couponprogram_partner_remove_customer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='fullname',
            new_name='full_name',
        ),
    ]
