# Generated by Django 4.0.3 on 2022-04-08 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_fullname_partner_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponprogram',
            name='expired_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='couponprogram',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
