# Generated by Django 4.0.3 on 2022-04-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_couponprogram_expired_date_couponprogram_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='couponprogram',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pos',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='posdetail',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uom',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uomcategory',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
