# Generated by Django 4.0.3 on 2022-04-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_coupon_active_couponprogram_active_partner_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponprogram',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='couponprogram',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed Amount')], default='percent', max_length=50),
        ),
    ]
