# Generated by Django 4.0.3 on 2022-04-09 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_couponprogram_discount_couponprogram_discount_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
