# Generated by Django 4.0.3 on 2022-04-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_partner_is_customer_partner_is_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='dob',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='full_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
