# Generated by Django 4.0.3 on 2022-04-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_partner_dob_alter_partner_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='couponprogram',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='posdetail',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uom',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uomcategory',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
