# Generated by Django 4.0.3 on 2022-04-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_coupon_active_alter_couponprogram_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posdetail',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
