# Generated by Django 4.0.3 on 2022-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_partner_dob_alter_partner_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('shipping', 'Shipping'), ('done', 'Done')], default='draft', max_length=100),
        ),
    ]
