# Generated by Django 4.0.3 on 2022-04-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_pos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
