# Generated by Django 4.0.3 on 2022-04-14 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_partner_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pos',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.partner'),
        ),
    ]
