# Generated by Django 4.0.3 on 2022-04-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_pos_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='phone',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
