# Generated by Django 3.2.12 on 2022-04-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20220416_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupon_programs',
            field=models.ManyToManyField(to='store.CouponProgram'),
        ),
    ]
