# Generated by Django 3.2.12 on 2022-04-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_remove_product_coupon_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponprogram',
            name='products',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
