# Generated by Django 3.2.12 on 2022-04-16 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_couponprogram_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='amount_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='posdetail',
            name='amount_price',
            field=models.FloatField(default=0),
        ),
    ]
