# Generated by Django 3.2.12 on 2022-04-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20220416_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='posdetail',
            name='sub_price_unit',
            field=models.FloatField(default=0),
        ),
    ]
