# Generated by Django 4.0.3 on 2022-04-17 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_pos_amount_discount_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sub_price',
        ),
    ]
