# Generated by Django 4.0.3 on 2022-04-18 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_remove_product_sub_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='POS',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='POSDetail',
            new_name='OrderDetail',
        ),
        migrations.RenameField(
            model_name='coupon',
            old_name='pos',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='pos',
            new_name='order',
        ),
    ]
