# Generated by Django 4.0.3 on 2022-04-19 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_remove_order_status_alter_orderdeliver_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderdeliver', to='store.orderdeliver'),
        ),
        migrations.AlterField(
            model_name='orderdeliver',
            name='order',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='store.order'),
        ),
    ]
