# Generated by Django 4.0.3 on 2022-04-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_order_status_alter_orderdeliver_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='deliver',
        ),
    ]
