# Generated by Django 4.0.3 on 2022-04-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0041_alter_orderdeliver_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='deliver',
            new_name='orderdeliver',
        ),
    ]
