# Generated by Django 4.0.3 on 2022-04-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0045_alter_orderdeliver_completed_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdeliver',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
