# Generated by Django 4.0.3 on 2022-04-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0047_alter_partner_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='order',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='program',
        ),
        migrations.RemoveField(
            model_name='couponprogram',
            name='products',
        ),
        migrations.RemoveField(
            model_name='order',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderdeliver',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='orderdeliver',
            name='completed_user',
        ),
        migrations.RemoveField(
            model_name='orderdeliver',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='orderdeliver',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='user',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uom',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='uom',
            name='category',
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.DeleteModel(
            name='CouponProgram',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderDeliver',
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.DeleteModel(
            name='Partner',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='UOM',
        ),
        migrations.DeleteModel(
            name='UOMCategory',
        ),
    ]
