# Generated by Django 4.0.3 on 2022-04-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Chưa thanh toán'), ('confirmed', 'Đã tiếp nhận'), ('processing', 'Đang xử lý'), ('shipping', 'Đang giao hàng'), ('done', 'Hoàn thành'), ('canceled', 'Đã hủy')], default='draft', max_length=100),
        ),
    ]
