# Generated by Django 4.0.3 on 2022-04-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdeliver',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='orderdeliver',
            name='completed_date',
        ),
        migrations.AlterField(
            model_name='couponprogram',
            name='products',
            field=models.ManyToManyField(related_name='couponprograms', to='sale.product'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa giải quyết'), ('awaiting_payment', 'Đang thanh toán'), ('awaiting_fulfillment', 'Thanh toán thành công'), ('awaiting_shipment', 'Chờ shipper nhận hàng'), ('awaiting_pickup', 'Chờ khách hàng nhận hàng'), ('partially_shipped', 'Đã giao hàng một phần'), ('shipped', 'Đã giao hàng'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy'), ('declined', 'Đã từ chối'), ('partially_refunded', 'Đã hoàn lại một phần'), ('refunded', 'Đã hoàn lại'), ('disputed', 'Đang tranh chấp')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderdeliver',
            name='status',
            field=models.CharField(choices=[('pending', 'Chưa giải quyết'), ('awaiting_payment', 'Đang thanh toán'), ('awaiting_fulfillment', 'Thanh toán thành công'), ('awaiting_shipment', 'Chờ shipper nhận hàng'), ('awaiting_pickup', 'Chờ khách hàng nhận hàng'), ('partially_shipped', 'Đã giao hàng một phần'), ('shipped', 'Đã giao hàng'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy'), ('declined', 'Đã từ chối'), ('partially_refunded', 'Đã hoàn lại một phần'), ('refunded', 'Đã hoàn lại'), ('disputed', 'Đang tranh chấp')], default='pending', max_length=100),
        ),
    ]
