# Generated by Django 4.0.3 on 2022-04-27 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_remove_orderdeliver_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='sale.partner'),
        ),
    ]
