# Generated by Django 4.0.3 on 2022-04-27 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0004_address_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdeliver',
            name='completed_user',
        ),
        migrations.RemoveField(
            model_name='orderdeliver',
            name='created_user',
        ),
        migrations.RemoveField(
            model_name='orderdeliver',
            name='started_date',
        ),
        migrations.AddField(
            model_name='orderdeliver',
            name='started_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='started_orderdelivers', to=settings.AUTH_USER_MODEL),
        ),
    ]
