# Generated by Django 4.0.3 on 2022-04-29 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_remove_orderdeliver_completed_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponprogram',
            name='rule_customer',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='couponprogram',
            name='rule_product',
            field=models.JSONField(),
        ),
    ]
