# Generated by Django 4.0.3 on 2022-04-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0007_couponprogram_rule_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponprogram',
            name='rule_customer',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='couponprogram',
            name='rule_order',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='couponprogram',
            name='rule_product',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
